name: CI
on:
  workflow_dispatch:
  push:

jobs:
  check_hash:
    runs-on: ubuntu-latest
    outputs:
      after: ${{ steps.after.outputs.hash }}
    steps:
      - uses: actions/checkout@v2
      - run: |
          git rev-parse HEAD > ../dev_hash
      - id: after
        run: echo "::set-output name=hash::$(cat dev_hash | tr -d '\n')"

  android-build:
    runs-on: ubuntu-latest
    needs: [ check_hash ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          # flutter-version: '2.5.2'
          channel: 'stable'
      - name: Build
        run: |
          flutter clean
          flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk-build
          path: ./build/app/outputs/apk/release/app-release.apk
      
  release:
    runs-on: ubuntu-latest
    needs: [ check_hash, android-build ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: apk-build
          path: ./      
      - run: find . -type f -name '*.apk'
      - name: Release AppImage
        uses: marvinpinto/action-automatic-releases@latest
        with:
          title: ${{ needs.check_hash.outputs.after }}
          automatic_release_tag: "${{ needs.check_hash.outputs.after }}"
          prerelease: true
          draft: false
          files: |
            *.apk
            *.ipa
          repo_token: ${{ secrets.GITHUB_TOKEN }}
